config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations', :invitations => 'users/invitations' }
  get 'welcome/index'

  resources :projects do
    resources :tickets
  end
  
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       #if user.admin?
         can :create, Project
         can :manage, Project, :owner_id => user.id 
         can :create, Ticket
    can :manage, Ticket, :project => {:owner_id => user.id}    
           #else
         can :read, :all
       #else
         #can :read, :all
         #cannot :update, Project
       #end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, dependent: :destroy
  has_and_belongs_to_many :members, :class_name =>"User", :foreign_key =>"member_project_id", :association_foreign_key => "member_id"
  validates :title, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  
  validates :title, :description, :priority, presence: true
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  validates_attachment_file_name :picture, :matches => [/gif\Z/, /png\Z/, /jpe?g\Z/, /doc\Z/, /xls\Z/, /ppt\Z/]
  validates_with AttachmentSizeValidator, :attributes => :picture, :less_than => 1.megabytes
  attr_accessor :remove_picture
  
  before_save :delete_picture, if: ->{ remove_picture == '1' && !picture_updated_at_changed? }
  
  private
    def delete_picture
      self.picture = nil
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true
  validates :password, presence: true, if: Proc.new { |u| u.id.blank? }
  
  has_and_belongs_to_many :tickets
  has_and_belongs_to_many :member_projects, :class_name =>"Project", :foreign_key =>"member_id", :association_foreign_key => "member_project_id"
  
  include DeviseInvitable::Inviter
  
  def edit
    if User.exists?
      @user = User.find(params[:id])
    else
      redirect_to new_user_registration_path
    end
  end
  
  def full_name
    "#{first_name} #{last_name}"
    [first_name, last_name].join(" ")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :update_sanitized_params, if: :devise_controller?
  
  private
  def update
    if this
      redirect_to root_path
    else
      super
    end
  end

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email,:first_name, :last_name, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :first_name, :last_name, :password, :password_confirmation)}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :authenticate_user!, except:[:index]
  load_and_authorize_resource
  
  def index
    @projects = Project.all
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def new
    @project = Project.new
  end
  
  def edit
    @project = Project.find(params[:id])
  end
 
  def create
    @project = Project.new(project_params)
    
    @project.owner_id = current_user.id
    
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end
  
  def update
    @project = Project.find(params[:id])
 
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
 
    redirect_to projects_path
  end
 
  private
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.all
  end
  
  def show
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.find(params[:id])
  end
  
  def new
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.new
  end
  
  def edit
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.find(params[:id])
  end
  
  def create
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.create(ticket_params)
    @ticket.created_by_user = current_user.id
    redirect_to project_tickets_path(@project, @ticket)
  end
  
  def update
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.find(params[:id])
    if @ticket.update(ticket_params)
      redirect_to project_ticket_path(@project.id, @ticket)
    else
      render 'edit'
    end
  end
  
  def destroy
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.find(params[:id])
    @ticket.destroy
    redirect_to project_tickets_path(@project, @ticket)
  end
 
  private
  def ticket_params
    params.require(:ticket).permit(:title, :description, :priority, :difficulty, :status, :picture, :remove_picture, :attachment_name)
    end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
   # GET /resource/invitation/new
  def new
    self.resource = resource_class.new
    render :new
  end

  # POST /resource/invitation
  def create
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    if resource_invited
      if is_flashing_format? && self.resource.invitation_sent_at
        set_flash_message :notice, :send_instructions, :email => self.resource.email
      end
      respond_with resource, :location => after_invite_path_for(current_inviter)
      self.resource.member_projects<<Project.find(params[:user][:project_id])
    else
      respond_with_navigational(resource) { render :new }
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited
        this project from being saved:
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  = form_for :project, url: projects_path do |f|
    %p
      = f.label :title
      %br/
      = f.text_field :title
    %p
      = f.label :description
      %br/
      = f.text_area :description
      %br/
      %br/
    %p
      = f.submit
    

app/views/projects/edit.html.haml
.container
  %nav
    %ul.pagination
      %li= link_to '«', projects_path
  %h1 Edit

  = render 'form'

app/views/projects/index.html.haml
%table
  %tr
    %th
    %th{:colspan => "3"}
  - projects = Project.all
  - projects.each do |project|
    %tr
      %td
        %p{:style => "margin:10px; margin-left:0px"}
          %h3= link_to project.title, project
          %h5= project.created_at.strftime("%e %B %Y, %k:%M")
  - if projects.size == 0
    %em No Project Found    
%br/
%br/
%br/

app/views/projects/new.html.haml
%h1 New project:

= render 'form'

%br/
= link_to 'Back', projects_path

app/views/projects/show.html.haml
.container
  %nav
    %ul.pagination
      %li= link_to '«', projects_path
      - if can? :manage, @project
        %li= link_to 'Edit', edit_project_path(@project)
        %li= link_to 'Delete', project_path(@project), |
        method: :delete,                           |
        data: { confirm: 'Are you sure?' }         |
        %li= link_to 'Add co-worker', new_user_invitation_path(), metod: :get
      %li= link_to 'Tickets', project_tickets_path(@project, @ticket)
  %p
    %h1= @project.title
  %p
    %h5= @project.created_at.strftime("%e %B %Y, %k:%M")
    %br/
  %p
    = @project.description
  %br/
  %br/
      

app/views/tickets/_form.html.haml
%p
  = f.label :title
  %br/
  = f.text_field :title
%p
  - if @ticket.picture.present?
    = image_tag @ticket.picture.url(:medium)
    %br/      
    = f.check_box :remove_picture
    Remove attachment
  - else
    = f.file_field :picture
%p
  = f.label :attachment_name
  %br/
  = f.text_field :attachment_name
%p
  = f.label :description
  %br/
  = f.text_area :description
%p
  = f.label :priority
  %br/
  = f.select :priority, ['Low', 'Normal', 'High']
%p
  = f.label :difficulty
  %br/
  = f.select :difficulty, ['Easy', 'Medium','Hard']
%p
  = f.label :status
  %br/
  = f.select :status, ['Open', 'Closed', 'Canceled']
  %br/
  %br/
%p
  = f.submit

app/views/tickets/edit.html.haml
.container
  %nav
    %ul.pagination
      %li= link_to '«', project_tickets_path(@project, @ticket)
  %h1 Edit

  = form_for ([@project, @ticket]), :html => { :class => 'super', :multipart => true } do |f|
    = render :partial => 'form', :locals => { :f => f }
  %br/
  %br/

app/views/tickets/index.html.haml
.container
  %nav
    %ul.pagination
      %li= link_to '«', project_path(@project)
      %li= link_to 'Add', new_project_ticket_path
  %table
    %tr
      %th
      %th{:colspan => "3"}
    - tickets = @project.tickets.all
    - @project.tickets.each do |ticket|
      %tr
        %td
          %p{:style => "margin:10px; margin-left:0px"}
          %h3= link_to ticket.title,  [ticket.project, ticket]
          %h5= ticket.created_at.strftime("%e %B %Y, %k:%M")
    - if tickets.size == 0
      %em No Ticket Found
      %br/
      %br/

  %br/
  %br/

app/views/tickets/new.html.haml
.container
  %nav
    %ul.pagination
      %li= link_to '«', project_tickets_path(@project, @ticket)
  %h1 New ticket:

  - if @ticket.errors.any?
    #error_explanation
      %h2
        = pluralize(@ticket.errors.count, "error")
        prohibited
        this ticket from being saved:
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg

  = form_for ([@project, @project.tickets.build]), :html => { :class => 'super', :multipart => true } do |f|
    = render :partial => 'form', :locals => { :f => f }

  %br/
  %br/
  %br/

app/views/tickets/show.html.haml
.container
  %nav
    %ul.pagination
      %li= link_to '«', project_tickets_path(@project, @ticket)
      - if can? :ud, @ticket
        %li= link_to 'Edit', edit_project_ticket_path(@project, @ticket)
        %li= link_to 'Delete', [@ticket.project, @ticket], |
        method: :delete,                           |
        data: { confirm: 'Are you sure?' }         |
  %p
    %h1= @ticket.title
  %p
    %h5= @ticket.created_at.strftime("%e %B %Y, %k:%M")
    %br/
  %p
    = @ticket.attachment_name
    -if @ticket.picture.present?
      %br/
      = image_tag @ticket.picture.url(:medium)
      %br
  %p
    = @ticket.description
  %p
    %strong Priority:
    = @ticket.priority
  %p
    %strong Difficulty:
    = @ticket.difficulty
  %p
    %strong Status:
    = @ticket.status
  %br/
  %br/

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>

app/views/welcome/index.html.haml
.jumbotron
  .container4
    %h1.cover-heading Hello Rails! 
    %br/ 
    %br/
    %p.lead
      %button.btn.btn-success.btn-lg{:type => "button"}
        = link_to 'Projects', controller: 'projects'